### ISSUE TITLE
Issues with all Samsung 2.3.6-2.3.7 & Objectanimator

### ISSUE THREAD

**Issue by andacaydin** [JakeWharton/NineOldAndroids#44]
When Using Objectanimators in xml and trying to load via AnimatorInflater.loadAnimator() NumberFormatException occurs (Stacktrace follows).

I tested this bug with an older Samsung GT-B5510 and received several videos from the Samsung testcenter. Obviously the crash is related to an attribute already reserved by Samsungs Android-Derivate, possibly "android.R.attr.valueType" in AnimatorInflater:60. 

I will try to find a solution for this and fork the repo.
Stacktrace is with the samle app and "LoadAnimator", with a out-of-the-box Samsung GT-B5510.

01-01 20:42:06.968: E/AndroidRuntime(12807): FATAL EXCEPTION: main
01-01 20:42:06.968: E/AndroidRuntime(12807): java.lang.NumberFormatException
01-01 20:42:06.968: E/AndroidRuntime(12807):    at org.apache.harmony.luni.util.FloatingPointParser.parseFltImpl(Native Method)
01-01 20:42:06.968: E/AndroidRuntime(12807):    at org.apache.harmony.luni.util.FloatingPointParser.parseFloat(FloatingPointParser.java:321)
01-01 20:42:06.968: E/AndroidRuntime(12807):    at java.lang.Float.parseFloat(Float.java:323)
01-01 20:42:06.968: E/AndroidRuntime(12807):    at android.content.res.TypedArray.getFloat(TypedArray.java:287)
01-01 20:42:06.968: E/AndroidRuntime(12807):    at com.nineoldandroids.animation.AnimatorInflater.loadAnimator(AnimatorInflater.java:292)
01-01 20:42:06.968: E/AndroidRuntime(12807):    at com.nineoldandroids.animation.AnimatorInflater.loadObjectAnimator(AnimatorInflater.java:201)
01-01 20:42:06.968: E/AndroidRuntime(12807):    at com.nineoldandroids.animation.AnimatorInflater.createAnimatorFromXml(AnimatorInflater.java:149)
01-01 20:42:06.968: E/AndroidRuntime(12807):    at com.nineoldandroids.animation.AnimatorInflater.createAnimatorFromXml(AnimatorInflater.java:124)
01-01 20:42:06.968: E/AndroidRuntime(12807):    at com.nineoldandroids.animation.AnimatorInflater.loadAnimator(AnimatorInflater.java:102)
01-01 20:42:06.968: E/AndroidRuntime(12807):    at com.jakewharton.nineoldandroids.sample.apidemos.AnimationLoading$MyAnimationView.createAnimation(AnimationLoading.java:88)

**Comment by andacaydin** [comment]
Ok after some research, it seems to be similar to  https://github.com/JakeWharton/ActionBarSherlock/issues/317
in this case it's also the string "@16973911" which is causing the NumberFormatException unable to get parsed.
Workaround can be found in my fork.
