### ISSUE TITLE
NoSuchMethodError

### ISSUE THREAD

**Issue by AwesomelyAmazing** [JakeWharton/NineOldAndroids#58]
java.lang.NoSuchMethodError: android.view.View.setScrollY
        at com.nineoldandroids.view.ViewHelper$Honeycomb.setScrollY(ViewHelper.java:257)
        at com.nineoldandroids.view.ViewHelper.setScrollY(ViewHelper.java:127)

NEEDS_PROXY is set to false on post gingerbread devices and therefore view.setScrollY() is called, despite it being introduced in api 14

**Comment by JakeWharton** [comment]
Indeed it is. Good find. I'll try to get to this...

**Comment by jskierbi** [comment]
Bump :)
I've also run into this issue, only 3.x reporting crashes.
