### ISSUE TITLE
Demo crashes on Android 2.3.4

### ISSUE THREAD

**Issue by stepango** [JakeWharton/NineOldAndroids#8]
Nine old android demo 2.1.1 -> Toggles and ViewPropertyAnimator Demo crashes on my Xperia Ray with Android 2.3.4

**Comment by JakeWharton** [comment]
Do you have a stacktrace? Or could you install it from the Market and click 'Report' when it crashes?

**Comment by stepango** [comment]
Install from market and two reports sended.

**Comment by JakeWharton** [comment]
Awesome thanks. I did get one crash report from a Nexus One on 2.3.4 as well which is odd because I tested on 1.1, 1.5, 1.6, 2.2, and 2.3.3 in the emulator.

**Comment by JakeWharton** [comment]
The error seems to be this:

```
java.lang.NoClassDefFoundError: com.jakewharton.nineoldandroids.sample.VPADemo$1
at com.jakewharton.nineoldandroids.sample.VPADemo.onCreate(VPADemo.java:29)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1047)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:1623)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:1675)
at android.app.ActivityThread.access$1500(ActivityThread.java:121)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:943)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:130)
at android.app.ActivityThread.main(ActivityThread.java:3701)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:507)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:624)
at dalvik.system.NativeStart.main(Native Method)
```

Very odd behavior because the first anonymous inner-class would be the first click listener. I'm going to try to just rebuild the APK for the market as the sample runs fine when I compile it myself.

Forgot to mention that I see this too on a N1 @ 2.1 and a Galaxy Nexus @ 4.0.2

**Comment by JakeWharton** [comment]
New version deployed. After you receive the update please comment and/or close the issue if it worked.

**Comment by JakeWharton** [comment]
Works on all my stuff. Must have just been a bad build. Thanks for reporting.
